"""initial_schema

Revision ID: 499087b552e4
Revises: 
Create Date: 2026-04-12 14:04:25.977585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499087b552e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('par', sa.String(length=20), nullable=False),
    sa.Column('precio_min', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('precio_max', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cantidad_niveles', sa.Integer(), nullable=False),
    sa.Column('tipo_espaciado', sa.String(length=20), nullable=False),
    sa.Column('capital_usdc', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('apalancamiento', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeframe_simulacion', sa.String(length=5), nullable=False),
    sa.Column('pnl_total', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('pnl_porcentaje', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('trades_ganadores', sa.Integer(), nullable=False),
    sa.Column('trades_perdedores', sa.Integer(), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_drawdown_porcentaje', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('comisiones_totales', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fue_liquidado', sa.Boolean(), nullable=False),
    sa.Column('precio_liquidacion', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('timestamp_liquidacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capital_final', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('duracion_segundos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('par', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('par', 'timeframe', 'timestamp', name='uq_candle')
    )
    op.create_index('idx_candles_lookup', 'candles', ['par', 'timeframe', 'timestamp'], unique=False)
    op.create_table('grid_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('par', sa.String(length=20), nullable=False),
    sa.Column('precio_min', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('precio_max', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cantidad_niveles', sa.Integer(), nullable=False),
    sa.Column('tipo_espaciado', sa.String(length=20), nullable=False),
    sa.Column('capital_usdc', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('apalancamiento', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('modo', sa.String(length=10), nullable=False),
    sa.Column('es_favorita', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("modo IN ('testnet', 'mainnet')", name='chk_modo_grid'),
    sa.CheckConstraint("tipo_espaciado IN ('aritmetico', 'geometrico')", name='chk_tipo_espaciado'),
    sa.CheckConstraint('apalancamiento >= 1 AND apalancamiento <= 10', name='chk_apalancamiento'),
    sa.CheckConstraint('cantidad_niveles >= 2', name='chk_niveles_min'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_run_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lado', sa.String(length=4), nullable=False),
    sa.Column('precio', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('comision', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('nivel_grilla', sa.Integer(), nullable=False),
    sa.Column('capital_acumulado', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('posicion_neta', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bt_trades_run', 'backtest_trades', ['backtest_run_id'], unique=False)
    op.create_table('bot_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grid_config_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('precio_entrada_promedio', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('capital_inicial', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pnl_realizado', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('modo', sa.String(length=10), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('activo', 'pausado', 'detenido')", name='chk_estado'),
    sa.ForeignKeyConstraint(['grid_config_id'], ['grid_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('hyperliquid_order_id', sa.String(length=100), nullable=True),
    sa.Column('par', sa.String(length=20), nullable=False),
    sa.Column('lado', sa.String(length=4), nullable=False),
    sa.Column('precio', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('nivel_grilla', sa.Integer(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['bot_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_estado', 'orders', ['estado'], unique=False)
    op.create_index('idx_orders_session', 'orders', ['session_id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('par', sa.String(length=20), nullable=False),
    sa.Column('lado', sa.String(length=4), nullable=False),
    sa.Column('precio_fill', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cantidad_fill', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('comision', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pnl_realizado', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['bot_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fills_session', 'fills', ['session_id'], unique=False)
    op.create_index('idx_fills_timestamp', 'fills', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fills_timestamp', table_name='fills')
    op.drop_index('idx_fills_session', table_name='fills')
    op.drop_table('fills')
    op.drop_index('idx_orders_session', table_name='orders')
    op.drop_index('idx_orders_estado', table_name='orders')
    op.drop_table('orders')
    op.drop_table('bot_sessions')
    op.drop_index('idx_bt_trades_run', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_table('users')
    op.drop_table('grid_configs')
    op.drop_index('idx_candles_lookup', table_name='candles')
    op.drop_table('candles')
    op.drop_table('backtest_runs')
    op.drop_table('app_config')
    # ### end Alembic commands ###
